import jsPDF from 'jspdf';

interface ReportSection {
  title: string;
  content: string;
  metrics?: { label: string; value: string }[];
}

/**
 * Generate a Bloomberg-grade PDF report from QuantSuite data
 */
export function generateStockReportPDF(
  ticker: string,
  data: {
    currentPrice: number;
    change: number;
    changePercent: number;
    high52w: number;
    low52w: number;
    volatility: number;
    rsi14: number;
    sma20: number;
    sma50: number;
    sma200: number;
    momentum21d: number;
    momentum63d: number;
    signal: string;
    support: number;
    resistance: number;
  }
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('QUANTSUITE INSTITUTIONAL RESEARCH', 14, y);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth - 14, y, { align: 'right' });
  y += 8;

  // Divider
  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 10;

  // Ticker + Price
  doc.setFontSize(24);
  doc.setTextColor(30);
  doc.text(ticker, 14, y);
  
  doc.setFontSize(18);
  doc.setTextColor(data.change >= 0 ? 0 : 200, data.change >= 0 ? 150 : 50, data.change >= 0 ? 50 : 50);
  doc.text(`$${data.currentPrice.toFixed(2)}`, pageWidth - 14, y, { align: 'right' });
  y += 8;

  doc.setFontSize(11);
  doc.text(
    `${data.change >= 0 ? '+' : ''}${data.change.toFixed(2)} (${data.changePercent.toFixed(2)}%)  |  Signal: ${data.signal.toUpperCase()}`,
    14, y
  );
  y += 12;

  doc.line(14, y, pageWidth - 14, y);
  y += 10;

  // Key Metrics Table
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('KEY METRICS', 14, y);
  y += 8;

  const metrics = [
    ['52-Week High', `$${data.high52w.toFixed(2)}`],
    ['52-Week Low', `$${data.low52w.toFixed(2)}`],
    ['Annualized Volatility', `${data.volatility.toFixed(1)}%`],
    ['RSI (14)', data.rsi14.toFixed(1)],
    ['21-Day Momentum', `${data.momentum21d >= 0 ? '+' : ''}${data.momentum21d.toFixed(2)}%`],
    ['63-Day Momentum', `${data.momentum63d >= 0 ? '+' : ''}${data.momentum63d.toFixed(2)}%`],
  ];

  doc.setFontSize(9);
  doc.setTextColor(40);
  const colWidth = (pageWidth - 28) / 2;
  metrics.forEach(([label, value], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const xPos = 14 + col * colWidth;
    const yPos = y + row * 7;
    doc.setTextColor(100);
    doc.text(label, xPos, yPos);
    doc.setTextColor(30);
    doc.text(value, xPos + colWidth - 10, yPos, { align: 'right' });
  });
  y += Math.ceil(metrics.length / 2) * 7 + 8;

  // Moving Averages
  doc.setDrawColor(220);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('MOVING AVERAGES', 14, y);
  y += 8;

  const smaData = [
    ['SMA 20', `$${data.sma20.toFixed(2)}`, data.currentPrice > data.sma20 ? 'Above' : 'Below'],
    ['SMA 50', `$${data.sma50.toFixed(2)}`, data.currentPrice > data.sma50 ? 'Above' : 'Below'],
    ['SMA 200', `$${data.sma200.toFixed(2)}`, data.currentPrice > data.sma200 ? 'Above' : 'Below'],
  ];

  doc.setFontSize(9);
  smaData.forEach(([label, value, position], i) => {
    doc.setTextColor(100);
    doc.text(label, 14, y);
    doc.setTextColor(30);
    doc.text(value, 70, y);
    doc.setTextColor(position === 'Above' ? 0 : 200, position === 'Above' ? 130 : 50, position === 'Above' ? 50 : 50);
    doc.text(position, 110, y);
    y += 7;
  });
  y += 6;

  // Support/Resistance
  doc.setDrawColor(220);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('SUPPORT & RESISTANCE', 14, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(0, 130, 50);
  doc.text(`Support: $${data.support.toFixed(2)}`, 14, y);
  doc.setTextColor(200, 50, 50);
  doc.text(`Resistance: $${data.resistance.toFixed(2)}`, pageWidth / 2, y);
  y += 14;

  // Footer
  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 6;
  doc.setFontSize(7);
  doc.setTextColor(160);
  doc.text('This report is generated by QuantSuite for informational purposes only.', 14, y);
  doc.text('Not financial advice. Past performance is not indicative of future results.', 14, y + 4);

  doc.save(`${ticker}_QuantSuite_Report.pdf`);
}
